spring.application.name=THIS_IS_MY_CONFIG
server.port=8080

groq.api.key=${GROQ_API_KEY}

debug=false
spring.mongodb.uri=${SPRING_MONGODB_URI:${SPRING_DATA_MONGODB_URI:${MONGODB_URI}}}

spring.data.mongodb.auto-index-creation=true

jwt.secret=aichatbot-super-secret-key-must-be-at-least-256bits-long-for-hs256
jwt.expiration=86400000
